### ISSUE TITLE
Could not create lock file "/var/run/postgresql/.s.PGSQL.5432.lock"

### ISSUE THREAD

**Issue by radiusmk** [isaudits/docker-gvm#1]
I tried use GVM container, but I received the follow error: 

gvm           | (gvmd:777): md manage-WARNING **: 16:19:58.748: init_manage_process: sql_open failed
gvm           | Attempting to set max report rows to 5000
gvm           | Starting PostgreSQL...
gvm           | 2021-03-17 20:19:58.803 UTC [785] LOG:  listening on IPv6 address "::1", port 5432
gvm           | 2021-03-17 20:19:58.803 UTC [785] LOG:  listening on IPv4 address "127.0.0.1", port 5432
gvm           | Granting feed import owner rights to default user (admin) with UUID
gvm           | 2021-03-17 20:19:58.807 UTC [785] FATAL:  could not create lock file "/var/run/postgresql/.s.PGSQL.5432.lock": No such file or directory
gvm           | 2021-03-17 20:19:58.807 UTC [785] LOG:  database system is shut down
gvm           |
gvm           | (gvmd:787): md   main-CRITICAL **: 16:19:58.826: gvmd: g_option_context_parse: Missing argument for --value
gvm           | Starting Greenbone Vulnerability Manager...
gvm           | md   main:MESSAGE:2021-03-17 20h19.58 utc:778:    Greenbone Vulnerability Manager version 20.08.0 (DB revision 233)
gvm           | md manage:   INFO:2021-03-17 20h19.58 utc:778:    Creating user.
gvm           | md manage:WARNING:2021-03-17 20h19.58 utc:778: sql_open: PQconnectStart to 'gvmd' failed: could not connect to server: No such file or directory

I used the docker-compose.yml file on this repository.

Anyone have ideas to solve this problem?

tks.

**Comment by mcjon3z** [comment]
It appears that your database never fully initialized - this may be due to missing environment variables. I can't tell without seeing the entire console output.

Did you also create a local.env file within the /config folder based upon example.env?

**Comment by radiusmk** [comment]
Hello, 

I created config.env based on "example.env". When I start the container, the follow messages appear: 

gvm           | performing post-bootstrap initialization ... ok
gvm           | syncing data to disk ... ok
gvm           |
gvm           | WARNING: enabling "trust" authentication for local connections
gvm           | You can change this by editing pg_hba.conf or using the option -A, or
gvm           | --auth-local and --auth-host, the next time you run initdb.
gvm           |
gvm           | Success. You can now start the database server using:
gvm           |
gvm           |     /usr/lib/postgresql/10/bin/pg_ctl -D /var/lib/postgresql/data -l logfile start
gvm           |
gvm           | waiting for server to start....2021-03-17 16:42:48.902 EDT [351] FATAL:  could not create lock file "/var/run/postgresql/.s.PGSQL.5432.lock": No such file or directory
gvm           | 2021-03-17 16:42:48.902 EDT [351] LOG:  database system is shut down
gvm           |  stopped waiting
gvm           | pg_ctl: could not start server
gvm           | Examine the log output.
gvm           | createdb: could not connect to database template1: could not connect to server: No such file or directory
gvm           |         Is the server running locally and accepting
gvm           |         connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
gvm           | psql: could not connect to server: No such file or directory
gvm           |         Is the server running locally and accepting
gvm           |         connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
gvm           | psql: could not connect to server: No such file or directory
gvm           |         Is the server running locally and accepting
gvm           |         connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
gvm           | createuser: could not connect to database template1: could not connect to server: No such file or directory
gvm           |         Is the server running locally and accepting
gvm           |         connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
gvm           | psql: could not connect to server: No such file or directory
gvm           |         Is the server running locally and accepting
gvm           |         connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
gvm           | psql: could not connect to server: No such file or directory
gvm           |         Is the server running locally and accepting
gvm           |         connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
gvm           | psql: could not connect to server: No such file or directory
gvm           |         Is the server running locally and accepting
gvm           |         connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
gvm           | psql: could not connect to server: No such file or directory
gvm           |         Is the server running locally and accepting
gvm           |         connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
gvm           | psql: could not connect to server: No such file or directory
gvm           |         Is the server running locally and accepting
gvm           |         connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
gvm           | pg_ctl: PID file "/var/lib/postgresql/data/postmaster.pid" does not exist
gvm           | Is server running?

Inside the container I could see that /var/run/postgresql/ directory doesn't exist, I created that directory and set permissions for postgres user. After that, the postgres started successfully, but other erros appears, erros like "abc" role doesn't exist, probably because the postgres database needed start earlier. 

I think the problem is with the file permissions inside the image, but now I don't know how to fix it.  :(

Basicaly I cloned the repository with "git clone https://github.com/isaudits/docker-gvm/" and ran "docker-compose up".

Marco Aurélio

**Comment by mcjon3z** [comment]
May have been an update in the base image that changed something and those directories will need to be created and perms set on unit. I’ll check it out when I get a free minute. Thanks for the heads up.

Thanks,
Matt

Sent from mobile (please excuse any typos)
________________________________

**Comment by mcjon3z** [comment]
I just got around to testing and I was unable to duplicate the issue on a fresh pull and no existing volume data. Based on the error messages above, there does appear to be an issue with the socket directories not being properly initialized in the image build that you were running. This may have been a glitch in the Ubuntu repo that just happened to land on the build you were using, but I went ahead and added a line to the dockerfile to create and set permissions in the image just in case.

Go ahead and pull the updated image and see if that solves your problem.

`docker pull isaudits/gvm:gvm-20.8`

You may also want to wipe out the gvm_data and gvm_db docker volumes as well just in case something went sideways in those.

**Comment by radiusmk** [comment]
Thanks for reply. My problem was the docker version. I had success with Docker.CE.
