### ISSUE TITLE
Update to 21.4.x not possible it seems....

### ISSUE THREAD

**Issue by 4920441** [isaudits/docker-gvm#5]
Hi,

since today I get an "Report Outdated //EoL Scan Engine"  Error in every Report which is done past yesterday:
```

High (CVSS: 10.0)
NVT: Report outdated / end-of-life Scan Engine / Environment (local)
Summary
This script checks and reports an outdated or end-of-life scan engine for the following environments:
- Greenbone Source Edition (GSE)
- Greenbone Security Manager TRIAL (formerly Greenbone Community Edition (GCE))

```

I changed already   my yaml to 'latest'

`
image: isaudits/gvm:latest`

But latest seems not latest enough....

How do I update to a non EoL (Scanner) Version?

Thanks a lot!

Cheers

4920441

**Comment by mcjon3z** [comment]
Scanner components are built into the docker image. The newest round of releases from Greenbone do not build properly and have been temporarily been rolled back to the prior working version. See https://github.com/isaudits/docker-gvm/issues/4
